# Generated by Django 4.1.7 on 2023-04-24 06:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('productBrand', models.CharField(max_length=30)),
                ('productDateAdded', models.DateField()),
                ('productDimensions', models.CharField(max_length=20)),
                ('productImageUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(max_length=50)),
                ('User', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewText', models.TextField()),
                ('reviewDate', models.DateTimeField()),
                ('reviewRating', models.IntegerField()),
                ('reviewTitle', models.TextField()),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='api.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.user'),
        ),
    ]
