# Generated by Django 4.1.7 on 2023-03-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_username_alter_review_productname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='productName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='api.product'),
        ),
    ]
